### PR TITLE
fix giving a non-nullterminated string to libc::mkfifo

### PR DESCRIPTION
**Pull request by clonejo**

### CODE REVIEW

**Review by ibabushkin — COMMENTED** [review]
Hm, apparently I was over-eager when removing stuff. However, when did you notice this edge case to be hit?

**Comment by clonejo** [comment]
After updating to the current version (I was on a pretty old one) bartender kept creating a fifo in style of `/tmp/foo bar`. But only `/tmp/foo` was configured as a fifo and `bar` was another string from the config file.

**Comment by ibabushkin** [comment]
On 2017-10-25, Feiko Nanninga wrote:
> After updating to the current version (I was on a pretty old one)
> bartender kept creating a fifo in style of `/tmp/foo bar`. But only
> `/tmp/foo` was configured as a fifo and `bar` was another string from
> the configure file.

Hm, this sounds indeed suboptimal. Could you show me the configuration
snippet? Other than that, I'll merge the PR as-is.

**Comment by clonejo** [comment]
[bartenderrc.txt](https://github.com/ibabushkin/bartender/files/1417733/bartenderrc.txt)
```
# our format string:
format = """
[
{{{ cccac }}}
{{^ cccac }}
{"full_text": "not loaded", "color": "#404040"},
{{/cccac}}
{{{ ip }}}
 {{{ load }}}
 {{{ temperature }}}
 {{{ power }}}
 { "full_text": "{{{ date }}}" }
],
"""

[fifos.cccac]
fifo_path = "/tmp/cccac_fifo"

[timers.ip]
seconds = 30
command = "~/bin/bartender/ip.py"

[timers.load]
seconds = 5
command = "~/bin/bartender/load.py"

[timers.temperature]
seconds = 10
command = "~/bin/bartender/temperature.py"

[timers.power]
seconds = 60
command = "~/bin/bartender/power.py"

[timers.date]
seconds = 5
command = "date '+%a, %Y-%m-%d %H:%M:%S'"
```

Here, mkfifo was called with `/tmp/cccac_fifo temperature` and bartender subsequently crashed when it could not open the fifo at `/tmp/cccac_fifo`.

```
rustc --version
rustc 1.20.0 (f3d6973f4 2017-08-27)
```

**Comment by ibabushkin** [comment]
Ah, now I see. For some reason I assumed the strings we already used were null-terminated already, but apparently they're not (which makes sense if you think about it).

**Pull request merged**
